app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#test:
#    resource: "@AppBundle/Controller/"
#    prefix: /test

saveData:
    path:      /save_data
    defaults:  { _controller: AppBundle:Default:saveData }
    methods:  [POST]
