home:
    resource: "@AppBundle/Controller/"
    type:     annotation

saveData:
    path:      /save_data
    defaults:  { _controller: AppBundle:Default:saveData }
    methods:  [POST]

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
